In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from google.colab import files

In [3]:
uploaded = files.upload()

Saving hiring.csv to hiring.csv


In [4]:
import io
df = pd.read_csv(io.BytesIO(uploaded['hiring.csv']))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df.drop('experience',axis='columns',inplace=True)

In [27]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())
df

test_score(out of 10)  interview_score(out of 10)  salary($)
0                    8.0                           9      50000
1                    8.0                           6      45000
2                    6.0                           7      60000
3                   10.0                          10      65000
4                    9.0                           6      70000
5                    7.0                          10      62000
6                    8.0                           7      72000
7                    7.0                           8      80000

In [30]:
df.rename(columns={'salary($)':'salary'},inplace=True)
df

test_score(out of 10)  interview_score(out of 10)  salary
0                    8.0                           9   50000
1                    8.0                           6   45000
2                    6.0                           7   60000
3                   10.0                          10   65000
4                    9.0                           6   70000
5                    7.0                          10   62000
6                    8.0                           7   72000
7                    7.0                           8   80000

In [41]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
reg.coef_

array([ 47.08798017, 260.22304833])

In [38]:
reg.intercept_

60579.92565055762

In [42]:
reg.predict([[9.0,6]])

array([62565.05576208])

In [43]:
reg.predict([[10.0,10]])

array([63653.03593556])