In [2]:
import numpy as np

In [4]:
lst = [1,2,3,4,5]
nparray1 = np.array(lst)
print('nparray from list',nparray1)

nparray from list [1 2 3 4 5]


In [5]:
nparray2 = np.array([2,4,5,8])
print('nparray from list another way',nparray2)

nparray from list another way [2 4 5 8]


In [6]:
print('shape ',nparray2.shape)

shape  (4,)


In [7]:
print('Datatype ',nparray2.dtype)

Datatype  int64


In [8]:
nparray3 = np.array((2,5,6,7))
print(nparray3)

[2 5 6 7]


In [9]:
print ('Adding 2 to every element ',nparray3+2)

print ('Multiply  3 with every element ',nparray3*3)

Adding 2 to every element  [4 7 8 9]
Multiply  3 with every element  [ 6 15 18 21]


In [10]:
floatarry= np.array((2.9,3.0,6))
print('float array ',floatarry)
print('Datatype of float array ',floatarry.dtype)

float array  [2.9 3.  6. ]
Datatype of float array  float64


In [11]:
lst2d = [(1,2,3),(4,5,6)]
twodarray = np.array(lst2d)
print('twodarray ',twodarray)
print('2d Shape ',twodarray.shape)

twodarray  [[1 2 3]
 [4 5 6]]
2d Shape  (2, 3)


In [13]:
lst3d = [[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]
threedarray = np.array(lst3d)
print('threedarray ',threedarray)
print('3d Shape ',threedarray.shape)

threedarray  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3d Shape  (2, 2, 3)


In [14]:
zeros = np.zeros([3,3])
print('zeros ',zeros)

zeros  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
np.zeros((2,2), dtype=np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

In [16]:
ones = np.ones([4,3])
print('ones ',ones)
print('shape ',ones.shape)

ones  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape  (4, 3)


In [17]:
ones3d = np.ones([4,3,2])
print('ones3d ',ones3d)
print('shape ',ones3d.shape)

ones3d  [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
shape  (4, 3, 2)


In [18]:
e=np.array([(1,2,3),(4,5,6)])
print('Before reshape ',e)
er =e.reshape(3,2)
print('After reshape ',er)

Before reshape  [[1 2 3]
 [4 5 6]]
After reshape  [[1 2]
 [3 4]
 [5 6]]


In [19]:
print(e.flatten())

[1 2 3 4 5 6]


In [20]:
f=np.array([1,2,3])
g = np.array([4,5,6])
print('horizontal append ',np.hstack((f,g)))

horizontal append  [1 2 3 4 5 6]


In [21]:
print('Vertical Stack ',np.vstack((f,g)))

Vertical Stack  [[1 2 3]
 [4 5 6]]


In [22]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.81224525 4.72631886 5.28318408 4.89284443 5.10584076 5.21455437
 5.36363977 4.69668246 4.62893036 4.25800209]


In [24]:
A = np.matrix(np.ones((4,4)))
A

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [29]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [31]:
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [33]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [34]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [37]:
e  = np.array([(1,2,3), (4,5,6)])
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [40]:
print('Second column:', e[:,1])
print(e[1, :2])

Second column: [2 5]
[4 5]


In [41]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.30854285 5.58717584 5.66170873 5.05975953 4.34047107 5.32128298
 4.47192355 5.06121182 4.69272203 5.10716078]


In [42]:
print(np.min(normal_array))
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.308542850618623
5.661708725869479
4.961195918134704
5.060485673587044
0.46647363262381725


In [43]:
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [44]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [45]:
np.linalg.det(i)

-2.000000000000005