In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
from google.colab import files
uploaded = files.upload()


Saving homeprices (1).csv to homeprices (1).csv


In [6]:
import io
df = pd.read_csv(io.BytesIO(uploaded['homeprices (1).csv']))
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
df.price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [8]:
type(df.price)

pandas.core.series.Series

In [9]:
df[['area']]

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [10]:
type(df[['area']])

pandas.core.frame.DataFrame

In [11]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
model.coef_

array([135.78767123])

In [14]:
model.intercept_

180616.43835616432

In [15]:
model.predict([[5000]])

array([859554.79452055])

In [16]:
import pickle

In [17]:
with open('model_pickle_aug_2020','wb') as file:
    pickle.dump(model,file)

In [18]:
with open('model_pickle_aug_2020','rb') as file:
    mp = pickle.load(file)

In [19]:
mp.coef_

array([135.78767123])

In [20]:
mp.intercept_

180616.43835616432

In [21]:
mp.predict([[5000]])

array([859554.79452055])

In [22]:
from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [23]:
joblib.dump(model, 'model_joblib_aug_2020')

['model_joblib_aug_2020']

In [25]:
mj = joblib.load('model_joblib_aug_2020')

In [26]:
mj.coef_

array([135.78767123])

In [27]:
mj.intercept_

180616.43835616432

In [28]:
mj.predict([[5000]])

array([859554.79452055])